<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>IDVBuff.Survey.Persistence.Sqlite</RootNamespace>
    <AssemblyName>IDVB.Survey.Persistence.Sqlite</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Contracts\IDVBuff.Survey.Contracts.csproj" />
    <ProjectReference Include="..\Domain\IDVBuff.Survey.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.10" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="3.53.3" />
  </ItemGroup>
</Project>
