<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>IDVBuff.Survey.Contracts</RootNamespace>
    <AssemblyName>IDVB.Survey.Contracts</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Domain\IDVBuff.Survey.Domain.csproj" />
  </ItemGroup>
</Project>
