using System.Runtime.CompilerServices;
using OpenCvSharp;

namespace IDVBuff.Features.Maps;

/// <summary>
/// Status of scale estimation stage.
/// </summary>
public enum Vpsg3ScaleStatus
{
    Success = 0,
    PeakRatioBelowThreshold = 1,
    ScaleOutOfSupportedRange = 2,
    InsufficientEdgePixels = 3,
    DegenerateSignal = 4
}

/// <summary>
/// Result of the VPSG 3.0 scale estimation stage.
/// </summary>
public readonly record struct Vpsg3ScaleResult(
    Vpsg3ScaleStatus Status,
    double SeedScale,
    double PeakRatio,
    int Axis,
    string RejectReason)
{
    public bool Success => Status == Vpsg3ScaleStatus.Success;

    public static Vpsg3ScaleResult Failed(Vpsg3ScaleStatus status, string reason, double peakRatio = 0d) =>
        new(status, 1.0d, peakRatio, 0, reason);
}

/// <summary>
/// Coarse translation candidate generated by T-3 constellation bitset correlation.
/// </summary>
public readonly record struct Vpsg3TranslationCandidate(
    double OffsetX,
    double OffsetY,
    int RawScore,
    int Rank);

/// <summary>
/// Detailed spatial verification metrics across 2x2 quadrants.
/// </summary>
public readonly record struct Vpsg3SpatialResult(
    double GlobalScore,
    int TotalValidPoints,
    int HitPoints,
    int ValidPartitions,
    int PassedPartitions,
    bool IsSpatiallyConsistent);

/// <summary>
/// A locally refined candidate with joint sub-pixel scale and translation.
/// </summary>
public readonly record struct Vpsg3RefinedCandidate(
    double Scale,
    double OffsetX,
    double OffsetY,
    double WeightedScore,
    double K5Score,
    double K3Score,
    Vpsg3SpatialResult Spatial,
    int ProbesEvaluated);

/// <summary>
/// Decision output of the VPSG 3.0 verification gate.
/// </summary>
public readonly record struct Vpsg3GateResult(
    bool Passed,
    double Margin,
    bool HasDistinctRunnerUp,
    string FailureReason);

/// <summary>
/// Stage execution timing breakdown in milliseconds.
/// </summary>
public readonly record struct Vpsg3SolverStageTiming(
    double ExtractionMs,
    double ScaleMs,
    double TranslationMs,
    double RefineMs,
    double VerificationMs,
    double GateMs,
    double TotalMs);

/// <summary>
/// Final result of the VPSG 3.0 Fast Bootstrap solver.
/// Contains alignment transform, gate diagnostics, and stage timing.
/// Never invokes VPSG2 internally.
/// </summary>
public sealed class Vpsg3BootstrapResult
{
    public bool IsAccepted { get; }
    public bool IsFallback => !IsAccepted;
    public string FallbackReason { get; }

    public double Scale { get; }
    public double OffsetX { get; }
    public double OffsetY { get; }

    public double Confidence { get; }
    public double ApertureMargin { get; }
    public bool HasDistinctRunnerUp { get; }
    public int PassedPartitions { get; }

    public Vpsg3ScaleResult ScaleResult { get; }
    public Vpsg3RefinedCandidate BestCandidate { get; }
    public Vpsg3RefinedCandidate? RunnerUpCandidate { get; }
    public Vpsg3SolverStageTiming Timing { get; }

    public Vpsg3BootstrapResult(
        bool isAccepted,
        string fallbackReason,
        double scale,
        double offsetX,
        double offsetY,
        double confidence,
        double apertureMargin,
        bool hasDistinctRunnerUp,
        int passedPartitions,
        Vpsg3ScaleResult scaleResult,
        Vpsg3RefinedCandidate bestCandidate,
        Vpsg3RefinedCandidate? runnerUpCandidate,
        Vpsg3SolverStageTiming timing)
    {
        IsAccepted = isAccepted;
        FallbackReason = fallbackReason ?? string.Empty;
        Scale = scale;
        OffsetX = offsetX;
        OffsetY = offsetY;
        Confidence = confidence;
        ApertureMargin = apertureMargin;
        HasDistinctRunnerUp = hasDistinctRunnerUp;
        PassedPartitions = passedPartitions;
        ScaleResult = scaleResult;
        BestCandidate = bestCandidate;
        RunnerUpCandidate = runnerUpCandidate;
        Timing = timing;
    }

    public static Vpsg3BootstrapResult Fallback(
        string reason,
        Vpsg3ScaleResult scaleResult,
        Vpsg3SolverStageTiming timing) =>
        new(
            isAccepted: false,
            fallbackReason: reason,
            scale: scaleResult.SeedScale,
            offsetX: 0d,
            offsetY: 0d,
            confidence: 0d,
            apertureMargin: 0d,
            hasDistinctRunnerUp: false,
            passedPartitions: 0,
            scaleResult: scaleResult,
            bestCandidate: default,
            runnerUpCandidate: null,
            timing: timing);
}

/// <summary>
/// Reusable hot-path scratch buffers for zero steady-state managed allocations during VPSG 3.0 solving.
/// Thread-safe via thread-local or pooled instances.
/// </summary>
public sealed class Vpsg3SolverScratch
{
    [ThreadStatic]
    private static Vpsg3SolverScratch? _threadLocal;

    public static Vpsg3SolverScratch Current => _threadLocal ??= new Vpsg3SolverScratch();

    public double[] ProjectionBufferX { get; private set; } = new double[2048];
    public double[] ProjectionBufferY { get; } = new double[2048];
    public double[] CenteredSignalBuffer { get; private set; } = new double[2048];
    public double[] AutocorrBuffer { get; private set; } = new double[1024];

    public Point[] ScaledQueryPointsBuffer { get; } = new Point[256];
    internal int[] TranslationScores = [];
    public Vpsg3TranslationCandidate[] CandidateBuffer { get; } = new Vpsg3TranslationCandidate[64];
    internal int CandidateCount;
    public byte[] EdgeMaskBuffer { get; private set; } = new byte[1024 * 1024];

    internal void EnsureScaleCapacity(int width, int height)
    {
        var pixels = checked(width * height);
        if (EdgeMaskBuffer.Length < pixels) EdgeMaskBuffer = new byte[pixels];
        if (ProjectionBufferX.Length < width) ProjectionBufferX = new double[width];
        if (CenteredSignalBuffer.Length < width) CenteredSignalBuffer = new double[width];
        if (AutocorrBuffer.Length < width / 2) AutocorrBuffer = new double[width / 2];
    }
}
