<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>IDVBuff.Survey.Domain</RootNamespace>
    <AssemblyName>IDVB.Survey.Domain</AssemblyName>
  </PropertyGroup>
</Project>
