using OpenCvSharp;

namespace IDVBuff.Features.Maps;
internal static partial class MapStructureValidator
{

    internal static MapStructureRegistrationResult BuildLegacyResult(
        MapStructureRejectionReason rejectionReason,
        LegacyDiagnostics d,
        MapStructureCandidate[]? candidates = null,
        bool accepted = false,
        MapOverlayTransform? transform = null,
        double confidence = 0d,
        MapStructureConfidenceBreakdown? confidenceBreakdown = null,
        double bestScore = 0d,
        double secondScore = 0d,
        double candidateMargin = 0d,
        bool wasForcedBestCandidate = false,
        double featureConsensus = 0d,
        bool eccConverged = false,
        double eccCorrelation = 0d)
    {
        return BuildResult(rejectionReason,
            candidates: candidates,
            preprocessMs: d.PreprocessMs,
            searchMs: d.SearchMs,
            refineMs: d.RefineMs,
            queryConstructionMs: d.Ctx.QueryConstructionMs,
            historyCandidateMs: d.Ctx.HistoryCandidateMs,
            featureVotingMs: d.Ctx.FeatureVotingMs,
            pyramidSearchMs: d.Ctx.PyramidSearchMs,
            localTemplateSearchMs: d.Ctx.LocalTemplateSearchMs,
            globalTemplateSearchMs: d.Ctx.GlobalTemplateSearchMs,
            candidateRankingMs: d.CandidateRankingMs,
            debugDirectory: d.DebugDirectory,
            lockedScale: d.LockedScale,
            referenceWidth: d.ReferenceWidth,
            referenceHeight: d.ReferenceHeight,
            queryEdgePixels: d.QueryEdgePixels,
            queryBounds: d.QueryBounds,
            scaleHypothesisCount: d.ScaleHypothesisCount,
            oversizedHypothesisCount: d.OversizedHypothesisCount,
            usedRestrictedSearch: d.UsedRestrictedSearch,
            accepted: accepted,
            transform: transform,
            confidence: confidence,
            confidenceBreakdown: confidenceBreakdown,
            bestScore: bestScore,
            secondScore: secondScore,
            candidateMargin: candidateMargin,
            wasForcedBestCandidate: wasForcedBestCandidate,
            featureMatchCount: d.Ctx.FeatureMatchCount,
            featureInlierCount: d.Ctx.FeatureInlierCount,
            featureConsensus: featureConsensus,
            eccConverged: eccConverged,
            eccCorrelation: eccCorrelation,
            visibleMaskMs: d.VisibleMaskMs,
            visibleFraction: d.Ctx.VisibleAwareVisibleFraction ?? 0d,
            visibleStructurePixels: d.Ctx.VisibleAwareStructurePixels ?? 0,
            visibleEdgePixels: d.Ctx.VisibleAwareEdgePixels ?? 0,
            visibleAwareSearchMs: d.Ctx.VisibleAwareTotalMs,
            visibleAwareCandidateCount: d.Ctx.VisibleAwareCandidateCount,
            visibleAwareTopCost: d.Ctx.VisibleAwareBestCost,
            visibleAwareTopMargin: d.Ctx.VisibleAwareTopMargin,
            visibleAwareEarlyAccepted: d.Ctx.VisibleAwareEarlyAccepted,
            visibleAwareFallbackReason: d.Ctx.VisibleAwareFallbackReason,
            visibleAwareRequestedBackend: d.Ctx.VisibleAwareSession?.RequestedBackend ?? "",
            visibleAwareActualBackend: d.Ctx.VisibleAwareSession?.ActualBackend ?? "",
            visibleAwareUMatFallbackReason: d.Ctx.VisibleAwareSession?.FallbackReason,
            visibleAwareCoarseMs: d.Ctx.VisibleAwareCoarseMs,
            visibleAwareRefineMs: d.Ctx.VisibleAwareRefineMs,
            visibleAwareUploadMs: d.Ctx.VisibleAwareSession?.UploadMilliseconds ?? 0d,
            visibleAwareDownloadMs: d.Ctx.VisibleAwareSession?.DownloadMilliseconds ?? 0d,
            visibleAwareCompletedScales: d.Ctx.VisibleAwareCompletedScales,
            visibleAwareBudgetSkippedScales: d.Ctx.VisibleAwareBudgetSkippedScales,
            visibleAwareCoarsePeaks: d.Ctx.VisibleAwareCoarsePeaks,
            visibleAwareRefinedCandidates: d.Ctx.VisibleAwareRefinedCandidates,
            lowStructureRoute: d.LowStructurePlan?.Route.ToString(),
            lowStructureCompletedScaleCount: d.Ctx.ScalesEvaluated,
            lowStructureTranslationCandidateCount: d.Ctx.Candidates.Count,
            lowStructureBudgetTerminationReason: d.Ctx.TimeBudgetExceeded
                ? "budget-exceeded"
                : string.Empty,
            lowStructureVpsgEnabled: false);
    }
}
