[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [string]$RepositoryRoot,
    [Parameter(Mandatory)]
    [string]$OutputPath,
    [Parameter(Mandatory)]
    [string]$ProductVersion,
    [Parameter(Mandatory)]
    [string]$ReleaseLine,
    [string]$BuildVersion,
    [string]$CounterPath
)

$ErrorActionPreference = 'Stop'

$modulePath = Join-Path $RepositoryRoot 'installer\ReleaseVersion.psm1'
Import-Module $modulePath -Force -DisableNameChecking

$expectedProductParts = ConvertFrom-IDVBProductVersion -ProductVersion (Get-IDVBProductVersion -ReleaseLine $ReleaseLine)
$productParts = ConvertFrom-IDVBProductVersion -ProductVersion $ProductVersion
if ($productParts.Major -ne $expectedProductParts.Major -or $productParts.Minor -ne $expectedProductParts.Minor) {
    throw "IDVB product version '$ProductVersion' does not match release line '$ReleaseLine' (expected major.minor $($expectedProductParts.Major).$($expectedProductParts.Minor))."
}

if ([string]::IsNullOrWhiteSpace($BuildVersion)) {
    if ([string]::IsNullOrWhiteSpace($CounterPath)) {
        $CounterPath = Join-Path $RepositoryRoot '.idvb-build-count'
    }

    $BuildVersion = New-IDVBBuildVersion -ReleaseLine $ReleaseLine -CounterPath $CounterPath
}
else {
    $buildReleaseLine = $BuildVersion.Split('-', 2)[0]
    if ($buildReleaseLine -ne $ReleaseLine) {
        throw "IDVB build version '$BuildVersion' does not match release line '$ReleaseLine'."
    }
}

$numericVersion = ConvertTo-IDVBNumericVersion -PublicVersion $BuildVersion -Patch $productParts.Patch
$assemblyVersion = "$($productParts.BaseVersion).0"
$outputDirectory = Split-Path -Parent $OutputPath
if (-not [string]::IsNullOrWhiteSpace($outputDirectory)) {
    [void][System.IO.Directory]::CreateDirectory($outputDirectory)
}

function ConvertTo-CSharpStringLiteral {
    param([Parameter(Mandatory)][string]$Value)

    return '"' + $Value.Replace('\', '\\').Replace('"', '\"') + '"'
}

$source = @"
// <auto-generated />
using System.Reflection;

[assembly: AssemblyVersion($(ConvertTo-CSharpStringLiteral $assemblyVersion))]
[assembly: AssemblyFileVersion($(ConvertTo-CSharpStringLiteral $numericVersion))]
[assembly: AssemblyInformationalVersion($(ConvertTo-CSharpStringLiteral $BuildVersion))]

namespace IDVBuff;

internal static class BuildVersionInfo
{
    public const string ProductVersion = $(ConvertTo-CSharpStringLiteral $ProductVersion);
    public const string BuildVersion = $(ConvertTo-CSharpStringLiteral $BuildVersion);
    public const string NumericVersion = $(ConvertTo-CSharpStringLiteral $numericVersion);
}
"@

[System.IO.File]::WriteAllText($OutputPath, $source, [System.Text.UTF8Encoding]::new($false))
